# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Interest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Interest
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'FirebaseUI'
pod 'FirebaseUI'
pod 'TwitterCore', '<=2.8.0'
pod 'Firebase/Auth'
pod 'FirebaseUI/Google'
pod 'FirebaseUI/Twitter'

  target 'InterestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InterestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
